import type { Metadata } from "next";
import { Geist, Geist_Mono ,Vazirmatn } from "next/font/google";
import "./globals.css";
import Headers from "@/commponent/header";
import Footer from "@/commponent/footer";
import { faPhone } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const vazirmatn = Vazirmatn({
  subsets: ["arabic"],
  variable: "--font-vazirmatn",
  display: "swap",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${vazirmatn.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Headers/>
        <button
  className="
    fixed
    bottom-10 left-5
    w-14 h-14
    rounded-full
    bg-primary
    text-white
    text-2xl
    shadow-lg
    flex items-center justify-center
    z-50
    hover:scale-110
    transition-transform
  "
>
      <Link href="tel:03142316002">
            <FontAwesomeIcon className=" text-white text-xl w-6 h-6 " icon={faPhone} />
      </Link>
</button>
        {children}</body>
        <Footer/>
    </html>
  );
}
